# Generated by Django 5.1.6 on 2025-02-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilization',
            name='attributes',
            field=models.JSONField(default=list),
        ),
    ]
